### ISSUE TITLE
Implementace metody `show()`

### ISSUE THREAD

**Issue by JakubAndrysek** [C2Coder/Jaculus_oled#1]
Hned na začátek, super projekt. Na táboře to někteří zkoušeli a nikomu se to nepovedlo rozchodit do funkčního stavu.

Když jsem pracoval s několika grafickými knihovnami, tak většina při zavolání setPixel() nastavila správné hodnoty v nějakém schovaném poli. Následně po zavolání metody show() se toto pole vzalo a vykreslilo na displej.

**Comment by C2Coder** [comment]
Jo, takhle to dělám, funkce set_pixels, draw_array ... všechno to píše do bufferu a potom je funkce flip, která to vypíše na display.

**Comment by JakubAndrysek** [comment]
Ajó, sorry, tak to jsem se blbě mrknul 😅
